import type { Metadata } from 'next'
import { Geist } from 'next/font/google'
import '@/styles/globals.css'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
    display: 'swap',
    preload: true,
    adjustFontFallback: true,
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} bg-background font-sans antialiased text-primary! min-h-screen flex flex-col`}
            >
                <div className="flex-1 w-full">{children}</div>
            </body>
        </html>
    )
}
